theme: jekyll-theme-cayman
lang: "ru-RU" 

title: Online CV
description: A lot of thanks to Katot Does for idea!
author: Aidar Saifutdinov

url: https://saifutdinov.github.io

google_analytics: G-1C8Q33P8ES

plugins:
  - jekyll-feed
  - jekyll-seo-tag