theme: jekyll-theme-cayman

lang: "ru" 
languages: ["en", "ru", "es"]

default_lang: "ru"

title: Aidar Saifutdinov - Online CV
description: A lot of thanks to Katok Does for idea!
author: Aidar Saifutdinov

baseurl: "/ru"
url: https://saifutdinov.github.io

google_analytics: G-1C8Q33P8ES

plugins:
  - jekyll-feed
  - jekyll-seo-tag