title: "My Multi-language Resume"
description: "Многоязычное резюме на Jekyll"
# Если используете какую-то тему GitHub Pages (например minima):
# theme: minima

# Если нужно, чтобы ссылки работали корректно:
# baseurl: "/my-resume"
# url: "https://username.github.io"

# Локальные настройки (для примера)
languages:
  - ru
  - en
  - es

# Можно указать плагины (но помните, что GitHub Pages не все поддерживает):
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Другие настройки...
